[options]
Architecture = auto
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Nécessaire pour Wine 32-bit (lib32-*)
[multilib]
Include = /etc/pacman.d/mirrorlist
