---
defaultGroups:
    - users
    - wheel
    - storage
    - power
    - audio
    - video
    - network

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true

passwordRequirements:
    minLength: 4
    maxLength: -1

allowWeakPasswords: true
allowWeakPasswordsDefault: true

userShell: /bin/bash

hostname:
    location: EtcHostname
    writeHostsFile: true

requireStrongPasswords: false

presetUsername: ""
presetFullName: ""
presetHostname: "evoos-pc"
