---
showSupportUrl:         true
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    8
    requiredRam:        2
    internetCheckUrl:   https://archlinux.org
    check:
        - storage
        - ram
        - power
    required:
        - storage
        - ram
